### ISSUE TITLE
SftpUploader: add support for chmod

### ISSUE THREAD

**Issue by tschoonj** [rosalindfranklininstitute/rfi-file-monitor#125]

**Comment by LAShemilt** [comment]
Do we really want to do this?
I think it gives users too much power on remote systems...

**Comment by tschoonj** [comment]
Hmmm... well at the very least I need chmod for Miriam's uploads. Chown would probably only work when doing the transfer as root, so probably best to leave it out.

**Comment by LAShemilt** [comment]
is it just to transfer ownership of directories so we can write to them? or is to read? I just think that it is a bit insecure to maybe give a user the ability to make a whole directory structure writeable...

However, let's see how it is implemented and we can test it for robustness.
