### ISSUE TITLE
add post-processing support

### ISSUE THREAD

**Issue by LAShemilt** [rosalindfranklininstitute/rfi-file-monitor#157]
Some operations may require others to be completed before they can be launched, these operations may also require information generated by the previous operation in order to complete their function.

This was previously handled through the file.operational_metadata but it is lost in other engiens (specifically directory). A new mechanism for retrieving this information at a directory level needs to be built.

Using a decorator that returns operational metadata from a run method will be investigated.

**Comment by tschoonj** [comment]
Closed in #163
